# This Compose file is intended for local development, not production deployment.
#

version: "2.4"

services:

  hugo:
    image: jojomi/hugo:latest
    volumes:
      - .:/src
      - ../ukwa-site-build:/output
    environment:
      - HUGO_REFRESH_TIME=3600
      - HUGO_THEME=ukwa
      - HUGO_BASEURL=http://localhost:81

  nginx:
    image: nginx
    ports:
      - "81:80"
    volumes:
      - ../ukwa-site-build:/usr/share/nginx/html:ro

